services:
  lb:
    platform: linux/amd64
    image: nginx:1.27-alpine
    user: root
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "30MB"

  api1:
    platform: linux/amd64
    image: ${API_IMAGE:-rmoraes4/rinha-api-python3:latest}
    user: root
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-WARNING}"
      APP_LOG_EACH_REQUEST: "${APP_LOG_EACH_REQUEST:-0}"
      APP_DEBUG_TIMINGS: "${APP_DEBUG_TIMINGS:-0}"
      FRAUD_THRESHOLD: "${FRAUD_THRESHOLD:-0.6}"
    expose:
      - "8000"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160MB"

  api2:
    platform: linux/amd64
    image: ${API_IMAGE:-rmoraes4/rinha-api-python3:latest}
    user: root
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-WARNING}"
      APP_LOG_EACH_REQUEST: "${APP_LOG_EACH_REQUEST:-0}"
      APP_DEBUG_TIMINGS: "${APP_DEBUG_TIMINGS:-0}"
      FRAUD_THRESHOLD: "${FRAUD_THRESHOLD:-0.6}"
    expose:
      - "8000"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160MB"

networks:
  rinha:
    driver: bridge