worker_processes 1;
error_log /dev/stderr error;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log off;
    keepalive_timeout 15;
    keepalive_requests 10000;

    upstream api_servers {
        server api1:8000 max_fails=0;
        server api2:8000 max_fails=0;
        keepalive 64;
    }

    server {
        listen 9999;

        tcp_nodelay on;

        client_body_buffer_size 4k;
        client_max_body_size 4k;

        location / {
            proxy_pass http://api_servers;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_request_buffering off;
            proxy_buffering off;
            proxy_connect_timeout 200ms;
            proxy_send_timeout 2s;
            proxy_read_timeout 2s;
        }
    }
}